// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions } from '@tanstack/preact-query';

import { client } from '../client.gen';
import { getHello, type Options } from '../sdk.gen';
import type { GetHelloData, GetHelloResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getHelloQueryKey = (options?: Options<GetHelloData>) => createQueryKey('getHello', options);

/**
 * Return the scaffold greeting
 */
export const getHelloOptions = (options?: Options<GetHelloData>) => queryOptions<GetHelloResponse, DefaultError, GetHelloResponse, ReturnType<typeof getHelloQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getHello({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getHelloQueryKey(options)
});
