// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: idempotency.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimIdempotencyRequest = `-- name: ClaimIdempotencyRequest :one
INSERT INTO idempotency_requests (scope, key, request_hash, expires_at)
VALUES ($1, $2, $3, now() + interval '24 hours')
ON CONFLICT (scope, key) DO UPDATE
SET request_hash = EXCLUDED.request_hash, response_status = NULL,
    response_headers = NULL, response_body = NULL, expires_at = EXCLUDED.expires_at
WHERE idempotency_requests.expires_at <= now()
RETURNING id
`

type ClaimIdempotencyRequestParams struct {
	Scope       string
	Key         pgtype.UUID
	RequestHash []byte
}

func (q *Queries) ClaimIdempotencyRequest(ctx context.Context, arg ClaimIdempotencyRequestParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, claimIdempotencyRequest, arg.Scope, arg.Key, arg.RequestHash)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const completeIdempotencyRequest = `-- name: CompleteIdempotencyRequest :exec
UPDATE idempotency_requests
SET response_status = $1, response_headers = '{"Content-Type":["application/json"]}',
    response_body = $2
WHERE id = $3
`

type CompleteIdempotencyRequestParams struct {
	ResponseStatus *int16
	ResponseBody   []byte
	ID             pgtype.UUID
}

func (q *Queries) CompleteIdempotencyRequest(ctx context.Context, arg CompleteIdempotencyRequestParams) error {
	_, err := q.db.Exec(ctx, completeIdempotencyRequest, arg.ResponseStatus, arg.ResponseBody, arg.ID)
	return err
}

const getIdempotencyRequest = `-- name: GetIdempotencyRequest :one
SELECT id, created_at, scope, key, request_hash, response_status, response_headers, response_body, expires_at
FROM idempotency_requests WHERE scope = $1 AND key = $2
`

type GetIdempotencyRequestParams struct {
	Scope string
	Key   pgtype.UUID
}

func (q *Queries) GetIdempotencyRequest(ctx context.Context, arg GetIdempotencyRequestParams) (IdempotencyRequest, error) {
	row := q.db.QueryRow(ctx, getIdempotencyRequest, arg.Scope, arg.Key)
	var i IdempotencyRequest
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Scope,
		&i.Key,
		&i.RequestHash,
		&i.ResponseStatus,
		&i.ResponseHeaders,
		&i.ResponseBody,
		&i.ExpiresAt,
	)
	return i, err
}
