// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type FileKind string

const ()

func (e *FileKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FileKind(s)
	case string:
		*e = FileKind(s)
	default:
		return fmt.Errorf("unsupported scan type for FileKind: %T", src)
	}
	return nil
}

type NullFileKind struct {
	FileKind FileKind
	Valid    bool // Valid is true if FileKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFileKind) Scan(value interface{}) error {
	if value == nil {
		ns.FileKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FileKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFileKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FileKind), nil
}

type File struct {
	ID        pgtype.UUID
	CreatedAt time.Time
	Kind      FileKind
	BlobStore string
	Bucket    string
	ObjectKey string
}

type IdempotencyRequest struct {
	ID              pgtype.UUID
	CreatedAt       time.Time
	Scope           string
	Key             pgtype.UUID
	RequestHash     []byte
	ResponseStatus  *int16
	ResponseHeaders []byte
	ResponseBody    []byte
	ExpiresAt       time.Time
}

type User struct {
	ID        pgtype.UUID
	CreatedAt time.Time
}
