// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUser = `-- name: GetUser :one
SELECT id
FROM users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, userID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getUser, userID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
