// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetHello implements getHello operation.
//
// Return the scaffold greeting.
//
// GET /api/v1/hello
func (UnimplementedHandler) GetHello(ctx context.Context) (r *Hello, _ error) {
	return r, ht.ErrNotImplemented
}
