// Code generated by ogen, DO NOT EDIT.

package openapi

// Ref: #/components/schemas/Hello
type Hello struct {
	Content string `json:"content"`
}

// GetContent returns the value of Content.
func (s *Hello) GetContent() string {
	return s.Content
}

// SetContent sets the value of Content.
func (s *Hello) SetContent(val string) {
	s.Content = val
}
