// Code generated by MockGen. DO NOT EDIT.
// Source: health.go
//
// Generated by this command:
//
//	mockgen -source=health.go -destination=health_mock_test.go -package=health
//

// Package health is a generated GoMock package.
package health

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDatabasePinger is a mock of DatabasePinger interface.
type MockDatabasePinger struct {
	ctrl     *gomock.Controller
	recorder *MockDatabasePingerMockRecorder
	isgomock struct{}
}

// MockDatabasePingerMockRecorder is the mock recorder for MockDatabasePinger.
type MockDatabasePingerMockRecorder struct {
	mock *MockDatabasePinger
}

// NewMockDatabasePinger creates a new mock instance.
func NewMockDatabasePinger(ctrl *gomock.Controller) *MockDatabasePinger {
	mock := &MockDatabasePinger{ctrl: ctrl}
	mock.recorder = &MockDatabasePingerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabasePinger) EXPECT() *MockDatabasePingerMockRecorder {
	return m.recorder
}

// Ping mocks base method.
func (m *MockDatabasePinger) Ping(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockDatabasePingerMockRecorder) Ping(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockDatabasePinger)(nil).Ping), arg0)
}
