// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type Hello = {
    content: string;
};

/**
 * Client-generated UUID scoped by the application to the caller, operation, and resource.
 * Successful writes are replayed for 24 hours. Reusing a key with different input returns 409.
 *
 */
export type IdempotencyKey = string;

export type GetHelloData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/hello';
};

export type GetHelloResponses = {
    /**
     * Greeting
     */
    200: Hello;
};

export type GetHelloResponse = GetHelloResponses[keyof GetHelloResponses];
